steps:
  - label: ":whale::rstats: Build"
    command: docker/build

  - wait

  - label: ":docker: Test package installed"
    command: docker/test_package

  - wait

  - label: ":shipit: Push images"
    command: docker/push
